"""add employee password fields

Revision ID: da2fb54f8d5e
Revises: 3770a1073c2a
Create Date: 2026-09-06 17:40:53.713207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da2fb54f8d5e'
down_revision = '3770a1073c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        # server_default обязателен: в таблице уже есть 20 перенесённых
        # сотрудников, а колонка NOT NULL — без значения по умолчанию
        # Alembic не сможет проставить его в существующие строки.
        batch_op.add_column(
            sa.Column(
                'must_change_password',
                sa.Boolean(),
                nullable=False,
                server_default=sa.text('1'),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
